"""empty message

Revision ID: 002e6cab29b4
Revises: bd291dcde3aa
Create Date: 2024-08-27 21:32:13.119428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002e6cab29b4'
down_revision = 'bd291dcde3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_birthday',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birthday_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['birthday_id'], ['birthday.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'birthday_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_birthday')
    # ### end Alembic commands ###
