"""empty message

Revision ID: e47a963332b3
Revises: 002e6cab29b4
Create Date: 2024-09-02 22:18:33.528935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47a963332b3'
down_revision = '002e6cab29b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birthday', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('seven_day_notify')
        batch_op.drop_column('one_day_notify')
        batch_op.drop_column('same_day_notify')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seven_day_notify', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('one_day_notify', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('same_day_notify', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('same_day_notify')
        batch_op.drop_column('one_day_notify')
        batch_op.drop_column('seven_day_notify')

    with op.batch_alter_table('birthday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('same_day_notify', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('one_day_notify', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('seven_day_notify', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###
